### PR TITLE
Fix nullable and readonly/writeonly parsing

### LINKED ISSUE #68: Invalid nullable error
Hey all, im trying to parse a user response with a nullable field. While everything seems OK, I still get an error on the response.

<details>
  <summary>Relevant parts of generated schema</summary>

```json
            "ImageSchema": {
                "type": "object",
                "required": [
                    "id",
                    "identifier",
                    "type",
                    "full_url",
                    "dimensions",
                    "blur_hash",
                    "medium_url",
                    "thumb_url"
                ],
                "properties": {
                    "id": {
                        "format": "uuid",
                        "type": "string",
                        "example": "1053050b-dc52-40a4-b3cc-f97922ef5008"
                    },
                    "identifier": {
                        "type": "string"
                    },
                    "type": {
                        "enum": [
                            "image"
                        ],
                        "type": "string"
                    },
                    "mime_type": {
                        "type": "string",
                        "example": "image\/jpeg"
                    },
                    "size": {
                        "type": "integer"
                    },
                    "comment": {
                        "type": "string",
                        "nullable": true
                    },
                    "full_url": {
                        "format": "url",
                        "type": "string"
                    },
                    "medium_url": {
                        "format": "url",
                        "type": "string"
                    },
                    "thumb_url": {
                        "format": "url",
                        "type": "string"
                    },
                    "blur_hash": {
                        "type": "string"
                    },
                    "dimensions": {
                        "type": "object",
                        "properties": {
                            "width": {
                                "type": "integer"
                            },
                            "height": {
                                "type": "integer"
                            }
                        }
                    }
                },
                "maxProperties": 11,
                "nullable": true
            },

 "User": {
                "description": "All information about a user",
                "content": {
                    "application\/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "object",
                                    "required": [
                                        "id",
                                        "name",
                                        "email",
                                        "created_at",
                                        "updated_at"
                                    ],
                                    "properties": {
                                        "id": {
                                            "format": "uuid",
                                            "type": "string",
                                            "example": "3a163945-86a9-4767-bd89-03a8a01b4430"
                                        },
                                        "name": {
                                            "type": "string",
                                            "example": "John Doe"
                                        },
                                        "email": {
                                            "format": "email",
                                            "type": "string"
                                        },
                                        "created_at": {
                                            "format": "date-time",
                                            "type": "string",
                                            "example": "2021-10-23T13:19:29+00:00"
                                        },
                                        "updated_at": {
                                            "format": "date-time",
                                            "type": "string",
                                            "example": "2021-10-23T13:19:29+00:00"
                                        },
                                        "email_verified_at": {
                                            "format": "date-time",
                                            "type": "string",
                                            "nullable": true,
                                            "example": "2021-10-23T13:19:29+00:00"
                                        },
                                        "avatar": {
                                            "$ref": "#\/components\/schemas\/ImageSchema"
                                        }
                                    },
                                    "maxProperties": 7,
                                    "nullable": true
                                }
                            }
                        }
                    }
                }
            },

```
</details>

Here is the error I get from Spectator
<details>
    <summary>Error details</summary>

```
^ Illuminate\Testing\AssertableJsonString^ {#382
  +json: "{"exception":"Spectator\\Exceptions\\ResponseValidationException","message":"Error (Opis\\JsonSchema\\Validator): The properties must match schema: {properties}\n\n  Keyword: properties\n  Expected: {\"type\":\"object\",\"properties\":{\"data\":{\"maxProperties\":7,\"required\":[\"id\",\"name\",\"email\",\"created_at\",\"updated_at\"],\"type\":[\"object\",\"null\"],\"properties\":{\"id\":{\"type\":\"string\",\"format\":\"uuid\",\"example\":\"8b97c2c5-5b32-4d5f-be92-8c14ba12bfd0\"},\"name\":{\"type\":\"string\",\"example\":\"John Doe\"},\"email\":{\"type\":\"string\",\"format\":\"email\"},\"created_at\":{\"type\":\"string\",\"format\":\"date-time\",\"example\":\"2021-10-23T13:21:09+00:00\"},\"updated_at\":{\"type\":\"string\",\"format\":\"date-time\",\"example\":\"2021-10-23T13:21:09+00:00\"},\"email_verified_at\":{\"type\":\"string\",\"format\":\"date-time\",\"nullable\":true,\"example\":\"2021-10-23T13:21:09+00:00\"},\"avatar\":{\"maxProperties\":11,\"required\":[\"id\",\"identifier\",\"type\",\"full_url\",\"dimensions\",\"blur_hash\",\"medium_url\",\"thumb_url\"],\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\",\"format\":\"uuid\",\"example\":\"94085c6c-da65-4065-a8be-eac8f514a434\"},\"identifier\":{\"type\":\"string\"},\"type\":{\"enum\":[\"image\"],\"type\":\"string\"},\"mime_type\":{\"type\":\"string\",\"example\":\"image\\\/jpeg\"},\"size\":{\"type\":\"integer\"},\"comment\":{\"type\":\"string\",\"nullable\":true},\"full_url\":{\"type\":\"string\",\"format\":\"url\"},\"medium_url\":{\"type\":\"string\",\"format\":\"url\"},\"thumb_url\":{\"type\":\"string\",\"format\":\"url\"},\"blur_hash\":{\"type\":\"string\"},\"dimensions\":{\"type\":\"object\",\"properties\":{\"width\":{\"type\":\"integer\"},\"height\":{\"type\":\"integer\"}}}},\"nullable\":true}}}}}\n  Actual: {\"data\":{\"id\":\"220386da-d6a0-4024-aab1-776f5142274e\",\"name\":\"Brionna Mann\",\"email\":\"labadie.jamison@example.com\",\"created_at\":\"2021-10-23T13:21:11+00:00\",\"updated_at\":\"2021-10-23T13:21:11+00:00\",\"email_verified_at\":\"2021-10-23T13:21:11+00:00\",\"avatar\":{\"id\":\"083e5641-6e27-48b2-b177-5f5af2c291be\",\"identifier\":\"AmzcudK5R0dXjUVhLJmP.jpg\",\"type\":\"image\",\"size\":695,\"mime_type\":\"image\\\/jpeg\",\"comment\":null,\"blur_hash\":\"L009jvfQfQfQfQfQfQfQfQfQfQfQ\",\"dimensions\":{\"width\":10,\"height\":10},\"full_url\":\"https:\\\/\\\/generic.test\\\/image\\\/AmzcudK5R0dXjUVhLJmP.jpg?type=full\",\"thumb_url\":\"https:\\\/\\\/generic.test\\\/image\\\/AmzcudK5R0dXjUVhLJmP.jpg?type=thumb\",\"medium_url\":\"https:\\\/\\\/generic.test\\\/image\\\/AmzcudK5R0dXjUVhLJmP.jpg?type=medium\"}}}\n\n  ---","specErrors":["The properties must match schema: data","The properties must match schema: avatar","The properties must match schema: comment","The data (null) must match the type: string"]}"
  #decoded: array:3 [
    "exception" => "Spectator\Exceptions\ResponseValidationException"
    "message" => """
      Error (Opis\JsonSchema\Validator): The properties must match schema: {properties}\n
      \n
        Keyword: properties\n
        Expected: {"type":"object","properties":{"data":{"maxProperties":7,"required":["id","name","email","created_at","updated_at"],"type":["object","null"],"properties":{"id":{"type":"string","format":"uuid","example":"8b97c2c5-5b32-4d5f-be92-8c14ba12bfd0"},"name":{"type":"string","example":"John Doe"},"email":{"type":"string","format":"email"},"created_at":{"type":"string","format":"date-time","example":"2021-10-23T13:21:09+00:00"},"updated_at":{"type":"string","format":"date-time","example":"2021-10-23T13:21:09+00:00"},"email_verified_at":{"type":"string","format":"date-time","nullable":true,"example":"2021-10-23T13:21:09+00:00"},"avatar":{"maxProperties":11,"required":["id","identifier","type","full_url","dimensions","blur_hash","medium_url","thumb_url"],"type":"object","properties":{"id":{"type":"string","format":"uuid","example":"94085c6c-da65-4065-a8be-eac8f514a434"},"identifier":{"type":"string"},"type":{"enum":["image"],"type":"string"},"mime_type":{"type":"string","example":"image\/jpeg"},"size":{"type":"integer"},"comment":{"type":"string","nullable":true},"full_url":{"type":"string","format":"url"},"medium_url":{"type":"string","format":"url"},"thumb_url":{"type":"string","format":"url"},"blur_hash":{"type":"string"},"dimensions":{"type":"object","properties":{"width":{"type":"integer"},"height":{"type":"integer"}}}},"nullable":true}}}}}\n
        Actual: {"data":{"id":"220386da-d6a0-4024-aab1-776f5142274e","name":"Brionna Mann","email":"labadie.jamison@example.com","created_at":"2021-10-23T13:21:11+00:00","updated_at":"2021-10-23T13:21:11+00:00","email_verified_at":"2021-10-23T13:21:11+00:00","avatar":{"id":"083e5641-6e27-48b2-b177-5f5af2c291be","identifier":"AmzcudK5R0dXjUVhLJmP.jpg","type":"image","size":695,"mime_type":"image\/jpeg","comment":null,"blur_hash":"L009jvfQfQfQfQfQfQfQfQfQfQfQ","dimensions":{"width":10,"height":10},"full_url":"https:\/\/generic.test\/image\/AmzcudK5R0dXjUVhLJmP.jpg?type=full","thumb_url":"https:\/\/generic.test\/image\/AmzcudK5R0dXjUVhLJmP.jpg?type=thumb","medium_url":"https:\/\/generic.test\/image\/AmzcudK5R0dXjUVhLJmP.jpg?type=medium"}}}\n
      \n
        ---
      """
    "specErrors" => array:4 [
      0 => "The properties must match schema: data"
      1 => "The properties must match schema: avatar"
      2 => "The properties must match schema: comment"
      3 => "The data (null) must match the type: string"
    ]
  ]
}
```

</details>

Json blob expected schema: http://www.jsonblob.com/901459977663954944
Json blob actual response: http://www.jsonblob.com/901461043608567808

Any help on reading the error or pushing me in the right direction is much appreciated!

### LINKED ISSUE #99: Nullable seems to fail?
I suddenly get an error on code that has worked before.

response->dump() returns the following 👍 

`email_verified_at: string? <== The data (null) must match the type: string`

This seems wrong to me.. the `string?` type clearly states the nullable attribute is set.

The property is defined as 

`@OA\Property(property="email_verified_at",description="Email verified at",example="2021-01-27 11:23:45", format="date-time", type="string", nullable=true )`

Any clue how to figure out what is going on?

### LINKED ISSUE #132: Validation on nested object with `allOf` does not work correctly
I have the following case:

```
get:
  tags:
    - test
  summary: test
  description: test
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  allOf:
                    - type: object
                      properties:
                        id:
                          type: integer
                        NestedObject:
                          nullable: true
                          $ref: "NestedObject.yaml"
                    - $ref: "AnotherObject.yaml"
                    - $ref: "AnotherObject.yaml"
                          
```

Validation error:
```
 NestedObject: object++ <== The data (null) must match the type: object
```

it seems the `allOf` ignores the `nullable` tag and required all properties to not be null. 
The same code without `allOf`(manually merging objects) seems to work fine.

According to swagger's documentation if all objects in `allOf` are valid then the merged object is valid as well, but here this does not seem to be true.

### LINKED ISSUE #145: integer? <== The data (null) must match the type
I keep on getting issues like `y*: integer? <== The data (null) must match the type: integer` when y is part of an object in an array.

I know [this](https://github.com/hotmeteor/spectator/pull/25) exists, but somehow I cannot get rid of the error. 

Update:

I even get this problem in simple situations (but somehow not always in similar situations):

```
array <== All array items must match schema
    object <== The properties must match schema: product_id
        id*: integer
        product_id: integer? <== The data (null) must match the type: integer
```

(OpenAPI 3.0, Laravel 10, latest build)

### PR DESCRIPTION
**Pull request by bastien-phi**
`AbstractValidator::prepareData`has 2 objectives :
- transform the `nullable:true` openapi 3.0 format to the openapi 3.1 format adding `"null"` to the types
- remove readonly/writeonly properties depending on the context or preparation (request or response)

Original code had some issues in the implementation : 
- nullable transformation was only done on root object (and it's properties) but not on a root array for example. Same thing with attribute filtering
- the recursion was done 2 times, not exactly the same way
- nullable objects or array where not correctly prepared
- ...

I hope that this new implementation resolve all of these issues. Every field is prepared and the treatments are run recursively to inner fields. We now correctly apply 3.0->3.1 nullable migration and readonly/writeonly filtering.

Instead of looking at the type of the property, I chose to look at the attributes.
This way, for an object declared like
```yml
title: User
type: object
nullable: true
properties:
  email: 
    type: string
    nullable: true
```
will be correctly translated to Openapi 3.1 style
```yml
title: User
type:
  - object
  - 'null'
properties:
  email: 
    type: 
      - string
      - 'null'
```
which I think was not the case.

I tried to implement tests for each issue it closes but not sure I covered all the cases.

Fixes #68
Fixes #99
Fixes #132
Fixes #145

### CODE REVIEW

**Comment by hotmeteor** [comment]
@bastien-phi You want to resolve the conflict here? I'm not sure if both the `null` check and the `$data->properties` check should stay.

**Comment by bastien-phi** [comment]
I'm on it. Not sure what you are talking about...

I'll have to complete the testsuite, nullable dictionaries are not handled properly

**Comment by hotmeteor** [comment]
@bastien-phi Oh strange, it _was_ conflicting. Never mind!

**Review by hotmeteor — APPROVED** [review]
Nice updates!

**Pull request merged**
