### PR TITLE
Prepare v2

### PR DESCRIPTION
**Pull request by bastien-phi**
Adds a composer alias for v2 and upgrade guide.

It might need to be completed

### CODE REVIEW

**Comment by jarrodparkes** [comment]
@bastien-phi aside from updating docs, what else are you and @hotmeteor desiring for v2?

**Comment by bastien-phi** [comment]
I think it's possible to fix #140 before v2 but I did not have a lot of time recently because of client work.

I think I will get some time next week to push a couple of PRs. This would make v2 almost ready.

**Comment by hotmeteor** [comment]
@bastien-phi Right on

I've updated the README in this branch a little. If you have a minute, can you drop in this thread:

- any new methods you're aware of
- any new configs you're aware of
- any behaviors that have changed in v2

Basically anything you can think of that _might_be counter to what the docs did say.

I can take it from there, but you are much closer to all the nuances of the changes.

**Comment by bastien-phi** [comment]
@hotmeteor I think I already covered everything in the upgrade guide. I'll take a look on that but everything should be up-to-date

**Comment by bastien-phi** [comment]
@hotmeteor I may be wrong but  `Spectator::reset` is not documented

**Comment by bastien-phi** [comment]
I think we are close from V2. @jarrodparkes can you take a look on this ? Merging this will pre-release the V2 thanks to the composer alias.

@hotmeteor I will let you hit the release button when you want !

**Review by jarrodparkes — APPROVED** [review]
LGTM. I made a small change for a typo I noticed

**Comment by bastien-phi** [comment]
Thanks @jarrodparkes !

**Pull request merged**
