### PR TITLE
Refactor codebase, increase PHPStan level to 6

### PR DESCRIPTION
**Pull request by bastien-phi**
This PR also simplifies Middleware::validate as a parameter was not used anymore and makes usage of openapi version in RequestValidator::validate

### CODE REVIEW

**Comment by bastien-phi** [comment]
@hotmeteor @jarrodparkes  : As this PR is quite large, I requested reviews from both of you. Feel free to make comments

**Comment by jarrodparkes** [comment]
@bastien-phi taking a look now, thx!

**Review by hotmeteor — COMMENTED** [review]
Is `stdClass` the way to go over `object`? I didn't realize that.

**Comment by bastien-phi** [comment]
It looks like it : https://phpstan.org/r/2c329201-22fb-4786-bc59-e12f4258771e

`object` typehint means `any object` (any class) whereas `stdClass` is the actual class of `(object) $array`.

**Comment by bastien-phi** [comment]
@hotmeteor Is it ok for you ?

**Pull request merged**
